### ISSUE TITLE
Build a Creative Data Visualisation using Vega's APIs

### ISSUE THREAD

**Issue by SuDa2103** [vegaprotocol/bounties#12]
![Vega bounties](https://user-images.githubusercontent.com/149245/102112265-5e374e80-3e2f-11eb-88c6-61181f817f35.png)

Vega is a proof of stake blockchain for creating and trading derivatives. It provides infrastructure for decentralised markets that settle in assets held on Ethereum, and in future also Bitcoin and other major collateral blockchains. Vega facilitates high speed, permissionless derivatives markets. 

The Vega alpha mainnet showcases our technology and we are looking for passionate and talented members of the community to help us build out the vision by working with us to shape the end product.

Through a rich set of APIs, developers can build on top of the Vega network and build immersive web, mobile or desktop applications.

## Description

The task we’d like to see the Vega community get stuck into is building a visualisation based on some of the trading data that can be accessed through Vega’s APIs. 

Some good examples of this are:
- [XPRV’s staking dashboard](https://xprv-0.github.io/)
- [TX Street - an Ethereum data visualizer](https://txstreet.com/v/eth-btcr)

There are currently three API transport types on Vega: gRPC, GraphQL and REST. These are described in some detail in with a set API how-to guides (complete with code examples) on [https://docs.vega.xyz/](https://docs.vega.xyz/). 

Note: It is recommended you check out the docs to familiarise yourself with the current information. Also see the section below on "Familiarity with Vega" as this is an essential prerequisite.

This task is ideal for someone with Javascript knowledge and a passion for, or desire to learn REST, gRPC or GraphQL. We're looking for a front end client application with an interesting core visual element, highlighting either how vega blocks are being formed, either from many markets or a single one. We really want this to be as creative as possible, data points could include listing orders, streaming events, other market data etc.

## Acceptance criteria

- Design and create a showcase application and a set of supporting how-to guides that describe how the application works, primarily the queries made to Vega.
- The application should be web based. You are free to use whatever tools you choose. 
- Code and documentation should be open sourced under the MIT license.
- Design or CSS styling of the showcase app should somewhat align with the Vega branding.
- Bonus prizes available for the most unique visualisations - the wackier the better!!

## Familiarity with Vega

We're an exciting blockchain project with a recently launched alpha mainnet, we're adding new features all the time therefore we'd love anyone interested in completing our bounties to get to know our platform first. We feel it is very important for you to test out the platform, check out our documentation and understand the way the protocol works to complete our bounties to a high standard. We're friendly, open and helpful, so don't be afraid to ask questions.

## **How to Submit**

Publish your submission into a public Github repo with clear and informative README describing how to use it. Then, contact us on the [#Dev-General](https://discord.com/channels/720571334798737489/732948871948533791) channel on Vega’s discord

## **Bounty reward**

For this bounty, we will provide a bounty reward of up to **1000 DAI**, by working on the bounty you understand and accept that this is the reward total available. Finally, please check with us and keep in touch with the Vega team to ensure the solution is acceptable.

## **Resources for Developers**

- [Vega Documentation](https://docs.vega.xyz/)
- [Vega API Samples](https://github.com/vegaprotocol/sample-api-scripts)
- [Vega API clients](https://github.com/vegaprotocol/api/)
- [Vega Discord Chat](https://discord.gg/bkAF3Tu)
- [Vega Technical Overview Paper](https://vega.xyz/assets/vega-technical-overview.pdf)
- [Vega Whitepaper](https://vega.xyz/papers/vega-protocol-whitepaper.pdf)

## **Questions & Reviews**

You can reach out to us for any queries on our [#Dev-General](https://discord.com/channels/720571334798737489/732948871948533791) channel on Vega’s discord, or create a PR on this repo and we can help get you started 

We're a friendly team and are very keen to help where possible.

**We’re excited to see what you come up with! Time to BUIDL**

**Comment by 3scava1i3r** [comment]
Am i allowed to take this up?

**Comment by SuDa2103** [comment]
> Am i allowed to take this up?

Yes, absolutely! This bounty is open for submissions

**Comment by 3scava1i3r** [comment]
@SuDa2103 let's discuss more on the same in the discord

**Comment by 3scava1i3r** [comment]
@SuDa2103 it has been completed now,Here's the link for testing the same => https://vega-block-dashboard.netlify.app/
Let's discuss more on the payment and licensing this repository as well as soon as possible

**Comment by SuDa2103** [comment]
@3scava1i3r Thanks for the submission! @proofofjake and other members of the team will take it from here and reach out to you

**Comment by 3scava1i3r** [comment]
@SuDa2103 understood,will communicate with @proofofjake for next steps

**Comment by 3scava1i3r** [comment]
Any updates on the same?

**Comment by TouchstoneTheDev** [comment]
Have they offered you reward @3scava1i3r ?

**Comment by 3scava1i3r** [comment]
@TouchstoneTheDev it seems to be a communication gap,am working on it

**Comment by TouchstoneTheDev** [comment]
@SuDa2103 Any other bounties ?
I really appreciate the efforts 😊

**Comment by 3scava1i3r** [comment]
> @SuDa2103 Any other bounties ?
> I really appreciate the efforts 😊

Join the discord ser

**Comment by 3scava1i3r** [comment]
@SuDa2103 had some conversation with https://github.com/proofofjake and he asked me to contact you for the same

**Comment by TouchstoneTheDev** [comment]
> @SuDa2103 had some conversation with https://github.com/proofofjake and he asked my contact you for the same

I didn't got the second sentence !

**Comment by edd** [comment]
We've resolved this thread over on Discord, and for now I'm closing this issue & repo for now. The best place to find out about any future bounties would be Discord, or vega.xyz!

Thanks for your work @3scava1i3r!
